# Generated by Django 3.2.5 on 2021-07-27 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210727_0944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cast',
            unique_together={('movie', 'actor')},
        ),
    ]
